[package]
name = "jdepp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
cxx = "1.0"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
bindgen = "0.70"
cxx-build = "1.0"